table amazon
	lineageTag: a5537e63-9042-45f4-ae02-baac6819eff5

	column product_id
		dataType: string
		lineageTag: 1e418551-36d9-4cca-8706-06c194e3ddfe
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: 3f4d5664-7bb8-4926-a704-3d2a50eac994
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 0a691efa-1084-4ae3-b5b8-eab0d2125182
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column discounted_price
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: 926c8cfa-37f9-4945-8041-e493806047fc
		summarizeBy: sum
		sourceColumn: discounted_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column actual_price
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: e462aa36-79f1-4aff-a50e-d55c8e50dcf9
		summarizeBy: sum
		sourceColumn: actual_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column discount_percentage
		dataType: double
		lineageTag: 4942e2ff-b8e5-4a72-9769-63f4903385e7
		summarizeBy: sum
		sourceColumn: discount_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rating_count
		dataType: int64
		formatString: 0
		lineageTag: f4eb96a0-0909-4278-8762-dcbe7cc9e3b3
		summarizeBy: sum
		sourceColumn: rating_count

		annotation SummarizationSetBy = Automatic

	column about_product
		dataType: string
		lineageTag: 80e1eb24-b6c2-4120-9874-418075a46da1
		summarizeBy: none
		sourceColumn: about_product

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: string
		lineageTag: 207ecc36-fba8-4b5b-992e-28730b89844f
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column user_name
		dataType: string
		lineageTag: 46b3967c-3c7e-452e-be58-358b6c8b7460
		summarizeBy: none
		sourceColumn: user_name

		annotation SummarizationSetBy = Automatic

	column review_id
		dataType: string
		lineageTag: 3b618d45-e488-439d-a982-60f93f1ef02e
		summarizeBy: none
		sourceColumn: review_id

		annotation SummarizationSetBy = Automatic

	column review_title
		dataType: string
		lineageTag: 30f28149-ab62-42b9-ae45-cd2028972d39
		summarizeBy: none
		sourceColumn: review_title

		annotation SummarizationSetBy = Automatic

	column review_content
		dataType: string
		lineageTag: 66b7db64-d597-4ead-911b-e94265fb1296
		summarizeBy: none
		sourceColumn: review_content

		annotation SummarizationSetBy = Automatic

	column img_link
		dataType: string
		lineageTag: e2927980-b66b-4113-86c9-ed674e483968
		summarizeBy: none
		sourceColumn: img_link

		annotation SummarizationSetBy = Automatic

	column product_link
		dataType: string
		lineageTag: 79922cd2-1dcf-465d-a31d-57dd3a62b5c5
		summarizeBy: none
		sourceColumn: product_link

		annotation SummarizationSetBy = Automatic

	partition amazon = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Maneesha\OneDrive\Documents\PowerBI\PBIVersionControl\amazon.csv"),[Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", type text}, {"product_name", type text}, {"category", type text}, {"discounted_price", Currency.Type}, {"actual_price", Currency.Type}, {"discount_percentage", Percentage.Type}, {"rating", type number}, {"rating_count", Int64.Type}, {"about_product", type text}, {"user_id", type text}, {"user_name", type text}, {"review_id", type text}, {"review_title", type text}, {"review_content", type text}, {"img_link", type text}, {"product_link", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"rating"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

