table AMZN_data_1999_2022
	lineageTag: bbc0590f-09f4-455b-b714-c72523464828

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 62cda420-18c3-4f10-8d6d-f6e3fd885ff1
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: dbf9131e-3442-4aa7-b385-f0328c8bfea3
			defaultHierarchy: LocalDateTable_da39655f-cb7f-4f2a-a106-bc4ac3183350.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: 9fa3e35e-dd51-4bcc-8780-71252f500d52
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: e431326f-4e42-4a2b-878e-38450cc8dd69
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 836677b1-95a8-4a09-9d62-6f2096383413
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: 45c0f285-4a43-4c18-b06b-4cdb94128436
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: b08397a7-514a-4fe0-b3ac-219565d798b3
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: 97f51b1f-0252-4ede-be90-06b32db9d1e3
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN_data_1999_2022 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Maneesha\OneDrive\Documents\PowerBI Project\PBIVersionControl\AMZN_data_1999_2022.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

